// frontend/vuejs/src/app/traveling/components/UpdateOdometerView.vue
<template>
    <v-dialog v-model="viewModel.displayed" max-width="600px">
        <v-form v-if="viewModel.displayed"
                @submit.prevent="updateOdometer(viewModel.selectedCar.id)">
            <v-card>
                <v-card-title>
                    <v-icon large left>mdi-car</v-icon>
                    <span class="title font-weight-light">{{viewModel.titleText}}</span>
                </v-card-title>
                <v-card-text>
                    <v-text-field v-model="km"
                                  type="number"
                                  :label="viewModel.selectedCar.name"
                                  suffix="km"
                                  ref="carField"
                                  :placeholder="'Previously: '+viewModel.selectedCar.distance"
                    ></v-text-field>
                </v-card-text>

                <v-card-actions>
                    <v-spacer></v-spacer>
                    <v-btn flat color="secondary" @click="$travel.presenter.hideUpdateOdometer()">
                        {{viewModel.cancelText}}
                    </v-btn>
                    <v-btn type="submit" flat color="primary">{{viewModel.saveText}}</v-btn>
                </v-card-actions>
            </v-card>
        </v-form>
    </v-dialog>
</template>

<script lang="ts">
  import { Component, Vue, Watch } from 'vue-property-decorator';

  @Component
  export default class UpdateOdometerView extends Vue {
    viewModel = this.$travel.viewModel.updateOdometerView;
    km = '';

    updateOdometer(carId: string) {
      this.$travel.controller.updateOdometer(carId, this.km);
    }

    @Watch('viewModel.displayed') onDisplayChanged(displayed: boolean) {
      if (displayed) {
        this.km = '';
        setImmediate(() => {
          (this.$refs.carField as any).focus();
        });
      }
    }
  }
</script>

// src/frontend/reactts/traveling/compononents/UpdateOdometerView.tsx
import * as React from 'react';
import Dialog from '@material-ui/core/Dialog';
import DialogTitle from '@material-ui/core/DialogTitle';
import DialogContent from '@material-ui/core/DialogContent';
import TextField from '@material-ui/core/TextField';
import DialogActions from '@material-ui/core/DialogActions';
import Button from '@material-ui/core/Button';
import InputAdornment from '@material-ui/core/InputAdornment';
import { TravelingController, TravelingUI, TravelingViewModel } from '../../../interface-adapter';

interface UpdateOdometerViewProps {
  controller: TravelingController;
  viewModel: TravelingViewModel;
  presenter: TravelingUI;
}

export default class UpdateOdometerView extends React.Component<UpdateOdometerViewProps> {
  state = {
    km: '',
  };

  handleSubmit(event: any) {
    const carId = this.props.viewModel.updateOdometerView.selectedCar
      ? this.props.viewModel.updateOdometerView.selectedCar.id
      : '';
    this.props.controller.updateOdometer(carId, this.state.km);

    event.preventDefault();
  }

  handleChange(event: React.ChangeEvent<{ name?: string; value: unknown }>) {
    event.persist();
    this.setState(oldValues => ({
      ...oldValues,
      [event.target.name as string]: event.target.value,
    }));
  }

  render() {
    const carName = this.props.viewModel.updateOdometerView.selectedCar
      ? this.props.viewModel.updateOdometerView.selectedCar.name
      : '';
    const previously = this.props.viewModel.updateOdometerView.selectedCar
      ? this.props.viewModel.updateOdometerView.selectedCar.distance
      : '0';

    return (<Dialog open={this.props.viewModel.updateOdometerView.displayed}
                    onClose={() => this.props.presenter.hideUpdateOdometer()}
                    aria-labelledby="form-dialog-title">
      <form onSubmit={(event) => this.handleSubmit(event)}>
        <DialogTitle id="form-dialog-title">{this.props.viewModel.updateOdometerView.titleText}</DialogTitle>
        <DialogContent>
          <TextField name="km" label={carName} fullWidth
                     type="number"
                     onChange={(e) => this.handleChange(e)}
                     placeholder={'Previously: ' + previously}
                     InputProps={{
                       endAdornment: <InputAdornment
                         position="end">km</InputAdornment>,
                     }}

          />
        </DialogContent>
        <DialogActions>
          <Button onClick={() => this.props.presenter.hideUpdateOdometer()}
                  color="primary">{this.props.viewModel.updateOdometerView.cancelText}</Button>
          <Button color="primary" type="submit">{this.props.viewModel.updateOdometerView.saveText}</Button>
        </DialogActions>
      </form>
    </Dialog>);
  }
}
