// src/frontend/reactts/water/compononents/InitWaterMeterView.tsx
import * as React from 'react';
import { Card } from '@material-ui/core';
import CardContent from '@material-ui/core/CardContent';
import Typography from '@material-ui/core/Typography';
import CardActions from '@material-ui/core/CardActions';
import Button from '@material-ui/core/Button';
import { WaterController } from '../../../interface-adapter';

export default class InitWaterMeterView extends React.Component<{ controller: WaterController }> {
  render() {
    return (
      <Card>
        <CardContent>
          <Typography gutterBottom variant="h5" component="h2">
            Do you have different water meters for cold and hot water?
          </Typography>
          <Typography variant="body2" color="textSecondary" component="p">
            In some house, you can have 2 water meters, one for the cold water, the other for hot water.
          </Typography>
        </CardContent>
        <CardActions>
          <Button size="small" color="primary" onClick={() => this.props.controller.initialize(true)}>
            Cold-Hot
          </Button>
          <Button size="small" color="primary" onClick={() => this.props.controller.initialize(false)}>
            Standard
          </Button>
        </CardActions>
      </Card>
    );
  }
}

// frontend/src/app/water/components/InitWaterMeterView.vue
<template>
    <v-card>
        <v-card-title class="headline">Do you have different water meters for cold and hot water?</v-card-title>

        <v-card-text>In some house, you can have 2 water meters, one for the cold water, the other for hot water.
        </v-card-text>

        <v-card-actions>
            <v-spacer></v-spacer>
            <v-btn color="blue darken-4" flat="flat" @click="initWaterMeter(true)">Cold-Hot</v-btn>
            <v-btn color="blue darken-4" flat="flat" @click="initWaterMeter(false)">Standard</v-btn>
        </v-card-actions>
    </v-card>
</template>

<script lang="ts">
  import { Component, Vue } from 'vue-property-decorator';

  @Component({})
  export default class InitWaterMeterView extends Vue {
    async initWaterMeter(hasColdAndHotMeter: boolean) {
      await this.$water.controller.initialize(hasColdAndHotMeter);
    }
  }
</script>
