// frontend/vuejs/src/app/water/views/Home.vue
<template>
    <div v-if="viewModel.hasMeter">
        <v-btn
                style="bottom: 70px"
                color="indigo"
                key="add"
                dark
                fab
                fixed
                bottom
                right
                @click="presenter.showAddWaterConsumption()">
            <v-icon>mdi-plus</v-icon>
        </v-btn>

        <ListWaterConsumptionView/>
        <AddWaterConsumptionView/>

    </div>
    <div v-else>
        <InitWaterMeterView/>
    </div>
</template>

<script lang="ts">
  import { Component, Vue } from 'vue-property-decorator';
  import AddWaterConsumptionView from '@/app/water/components/AddWaterConsumptionView.vue';
  import ListWaterConsumptionView from '@/app/water/components/ListWaterConsumptionView.vue';
  import InitWaterMeterView from '@/app/water/components/InitWaterMeterView.vue';

  @Component({
    components: {
      InitWaterMeterView, AddWaterConsumptionView, ListWaterConsumptionView,
    },
  })
  export default class WaterConsumption extends Vue {
    presenter = this.$water.presenter;
    viewModel = this.$water.viewModel;

    async mounted() {
      this.$water.controller.refreshSummary();
    }

  }
</script>

// frontend/reactts/src/water/views/Home.tsx
import * as React from 'react';
import { ViewModel } from '@eco/frontend-interface-adapter/src/Water/ViewModel';
import Fab from '@material-ui/core/Fab';
import AddIcon from '@material-ui/icons/Add';
import withStyles from '@material-ui/core/styles/withStyles';
import { Theme } from '@material-ui/core';
import { NonFunctionProperties } from '../../shared-kernel/type/NonFunctionProperties';
import InitWaterMeterView from '../compononents/InitWaterMeterView';
import ListWaterMeterView from '../compononents/ListWaterConsumptionView';
import AddWaterConsumptionView from '../compononents/AddWaterConsumptionView';
import { WaterFactory } from '@eco/frontend-interface-adapter/src/Water/WaterFactory';

const styles = (theme: Theme) => {
  return {
    fab: {
      position: 'fixed',
      bottom: theme.spacing(9),
      right: theme.spacing(2),
    },
  };
};

interface HomeProps {
  waterFactory: WaterFactory;
}

@withStyles(styles)
export default class Home extends React.Component<HomeProps> {
  state: NonFunctionProperties<ViewModel> = { ...new ViewModel() };

  constructor(props: HomeProps) {
    super(props);
    this.props.waterFactory.viewModel.onChange((viewModel, newValues) => {
      this.setState({ ...newValues });
    });
    this.props.waterFactory.controller.refreshSummary();
  }

  render() {
    if (!this.state.hasMeter) {
      return (<InitWaterMeterView controller={this.props.waterFactory.controller}/>);
    }

    return (<div>
      <ListWaterMeterView label={this.props.waterFactory.viewModel}
                          consumptions={this.props.waterFactory.viewModel.consumptions}
                          controller={this.props.waterFactory.controller}/>
      <AddWaterConsumptionView
        controller={this.props.waterFactory.controller}
        viewModel={this.props.waterFactory.viewModel}
        presenter={this.props.waterFactory.presenter}/>

      <Fab color="primary" aria-label="Add" className={this.props.classes.fab}
           onClick={() => this.props.waterFactory.presenter.showAddWaterConsumption()}>
        <AddIcon/>
      </Fab>
    </div>);
  }
}
