// frontend/reactts/src/traveling/compononents/AddFlightView.tsx
import * as React from 'react';
import { TravelingController } from '@eco/frontend-interface-adapter/src/Traveling/TravelingController';
import { ViewModel } from '@eco/frontend-interface-adapter/src/Traveling/ViewModel';
import { TravelingUI } from '@eco/frontend-interface-adapter/src/Traveling/TravelingUI';
import Dialog from '@material-ui/core/Dialog';
import DialogTitle from '@material-ui/core/DialogTitle';
import DialogContent from '@material-ui/core/DialogContent';
import TextField from '@material-ui/core/TextField';
import { FormControl } from '@material-ui/core';
import InputLabel from '@material-ui/core/InputLabel';
import Select from '@material-ui/core/Select';
import MenuItem from '@material-ui/core/MenuItem';
import DialogActions from '@material-ui/core/DialogActions';
import Button from '@material-ui/core/Button';
import { AddFlightRequest } from '@eco/domain/src/Traveling/UseCase/AddFlight/AddFlightRequest';

interface AddFlightViewProps {
  controller: TravelingController;
  viewModel: ViewModel;
  presenter: TravelingUI;
}

export default class AddFlightView extends React.Component<AddFlightViewProps> {

  state: {
    km: string,
    seat: string,
    description: string,
  };

  constructor(props: AddFlightViewProps) {
    super(props);
    this.state = {
      km: '',
      seat: props.viewModel.addFlightView.seats[0],
      description: '',
    };
  }

  handleSubmit(event: any) {
    const request = new AddFlightRequest(this.state.seat, this.state.km, this.state.description);
    this.props.controller.addFlight(request);
    event.preventDefault();
  }

  handleChange(event: React.ChangeEvent<{ name?: string; value: unknown }>) {
    event.persist();
    this.setState(oldValues => ({
      ...oldValues,
      [event.target.name as string]: event.target.value,
    }));
    console.log(this.state);
  }

  render() {
    return (<Dialog open={this.props.viewModel.addFlightView.displayed}
                    onClose={() => this.props.presenter.cancelAddFlight()}
                    aria-labelledby="form-dialog-title">
      <form onSubmit={(event) => this.handleSubmit(event)}>
        <DialogTitle id="form-dialog-title">{this.props.viewModel.addFlightView.titleLabel}</DialogTitle>
        <DialogContent>
          <TextField autoFocus name="km" label="Distance" value={this.state.km} type="number" fullWidth
                     onChange={(e) => this.handleChange(e)}/>
          <FormControl fullWidth>
            <InputLabel htmlFor="seat">{this.props.viewModel.addFlightView.seatsLabel}</InputLabel>
            <Select id="seat" name="seat" value={this.state.seat} onChange={(e) => this.handleChange(e)}>
              {
                this.props.viewModel.addFlightView.seats.map((seat) => <MenuItem key={'seat_' + seat}
                                                                                 value={seat}>{seat}</MenuItem>)
              }

            </Select>
          </FormControl>
          <TextField name="description" label={this.props.viewModel.addFlightView.descriptionLabel} fullWidth
                     value={this.state.description}
                     onChange={(e) => this.handleChange(e)}/>
        </DialogContent>
        <DialogActions>
          <Button onClick={() => this.props.presenter.cancelAddFlight()}
                  color="primary">{this.props.viewModel.addFlightView.cancelLabel}</Button>
          <Button color="primary" type="submit">{this.props.viewModel.addFlightView.saveLabel}</Button>
        </DialogActions>
      </form>
    </Dialog>);
  }
}

// frontend/src/app/traveling/components/AddFlightView.vue
<template>
    <v-dialog v-model="viewModel.displayed" max-width="600px">
        <v-form @submit.prevent="addTravel">
            <v-card>
                <v-card-title>
                    <v-icon large left>mdi-airplane</v-icon>
                    <span class="title font-weight-light">{{viewModel.titleLabel}}</span>
                </v-card-title>
                <v-card-text>
                    <v-text-field v-model="km" type="number" label="Distance" ref="distance" suffix="km"></v-text-field>
                    <v-select v-model="seat"
                              :items="viewModel.seats"
                              :label="viewModel.seatsLabel"
                    ></v-select>
                    <v-text-field v-model="description" :label="viewModel.descriptionLabel"></v-text-field>
                </v-card-text>

                <v-card-actions>
                    <v-spacer></v-spacer>
                    <v-btn flat color="secondary" @click="presenter.cancelAddFlight()">{{viewModel.cancelLabel}}</v-btn>
                    <v-btn flat color="primary" type="submit">{{viewModel.saveLabel}}</v-btn>
                </v-card-actions>
            </v-card>
        </v-form>
    </v-dialog>
</template>

<script lang="ts">
  import { Component, Vue, Watch } from 'vue-property-decorator';
  import { AddFlightController } from '@/domain/Traveling/UseCase/AddFlight/AddFlightController';
  import { AddFlight } from '@/domain/Traveling/UseCase/AddFlight/AddFlight';
  import { AddFlightRequest } from '@/domain/Traveling/UseCase/AddFlight/AddFlightRequest';
  import { AddFlightPresenterInterface } from '@/domain/Traveling/UseCase/AddFlight/AddFlightPresenterInterface';

  @Component
  export default class AddFlightView extends Vue {
    presenter: AddFlightPresenterInterface = this.$travelingFactory.travelingHomePresenter;
    viewModel = this.presenter!.getAddFlightViewModel();
    controller = new AddFlightController(new AddFlight(this.presenter!));

    seat = this.viewModel.seats[0];
    km = '';
    description = '';

    async addTravel() {
      this.controller.addFlight(new AddFlightRequest(this.seat, this.km, this.description));
    }

    @Watch('viewModel.displayed') onDisplayedChanged(newValue: boolean) {
      if (newValue) {
        console.log('ici');
        this.clearForm();
        setImmediate(() => {
          (this.$refs.distance as any).focus();
        });
      }
    }

    private clearForm() {
      this.km = '';
      this.description = '';
      this.seat = this.viewModel.seats[0];
    }
  }
</script>
